# Generated by Django 3.2.7 on 2021-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211001_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
